version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'surecansell'
      POSTGRES_USER: 'surecansell'
      POSTGRES_PASSWORD: 'vsHt8Kvdrgk9N3vcVyd427eVp6WF8M9W'
    ports:
      - "5432:5432"
    volumes:
      - ./database_init:/docker-entrypoint-initdb.d
  wait:
    image: waisbrot/wait
    environment:
      TARGETS: 'db:5432'
    depends_on:
      - db
  app:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./static:/app/static
    depends_on:
      - wait